### PR TITLE
sync-up

### PR DESCRIPTION
**Pull request by the0ne**

### CODE REVIEW

**Comment by the0ne** [comment]
@jolivepetrus I verified all changes have been merged perfectly to the new structure! :+1:

**Comment by max1220** [comment]
Ah, finally I can use the HTTP server for real dynamic content!

**Comment by the0ne** [comment]
@jolivepetrus ready again to sync-up

**Comment by the0ne** [comment]
@max1220 nice to hear somebody except myself is actually using this =)

**Comment by the0ne** [comment]
@jolivepetrus I guess the changes in components/dropbear/svr-chansession.c come from eb720b0?

**Pull request merged**
