### PR TITLE
Added configuration for the WeMos ESP32 board with 128x64 OLED display

### PR DESCRIPTION
**Pull request by bytebang**
The out-of-the-box configuration of the GENERIC board has some issues and can not be used with the cheap Wemos® ESP32 OLED Modules :

- GDisplay has not enabled I2C 
- The I2C hardware configuration does not match the boards hardware layout
- The standard bluetooth implementation causes boot-loops because the heap memory is too low. 

This pull request implements the correct configuration for these boards which can be ordered for example here: https://www.banggood.com/Wemos-ESP32-OLED-Module-For-Arduino-ESP32-OLED-WiFi-Bluetooth-Dual-ESP-32-ESP-32S-ESP8266-p-1148119.html

image

Now the display can be used as shown in this example:
```lua
gdisplay.attach(gdisplay.SSD1306_128_64, gdisplay.LANDSCAPE, false, 0x3c)
gdisplay.clear()
gdisplay.setfont(gdisplay.UBUNTU16_FONT)
gdisplay.write({gdisplay.CENTER,gdisplay.CENTER},"Lua-RTOS-ESP32")
```

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
Hi @bytebang,

We are waiting to receive this board from our provider.
We need to check other hardware pin maps prior to accept your PR, because we need to check that this board works with The Whitecat IDE (https://ide.whitecatboard.org).

Bet regards,

Jaume

**Comment by bytebang** [comment]
Tell me what you need. 
Maybe I can help you.

**Comment by oskarirauta** [comment]
I can verify that with minor changes this patch is working.
I had issues with WiFi with Wemos LoLin32 board - on all variants (I tried with Generic ESP32 and ESP32 Core board).

But with minor modified bytebang's version I finally got WiFi working.
ByteBang, please test WiFi functionality with your board. 

The problem was that Wifi wasn't able to connect/to be available for connecting after establishing a link. Scanning worked and I was able to join network, but trying to ping anywhere or be pingable, was the issue. My board received IP 10.0.0.154/255.255.0.0 in my network and was able to ping it's own IP address and also 127.0.0.1 but for example, pinging gateway/dns (10.0.0.1) was impossible. Also, from gateway or computer in my network, IP 10.0.0.154 was unreachable. DNS reported that device with certain MAC address had requested IP and IP 10.0.0.154 was served. It also authenticated properly for WPA2-PSK.

Changes that I made were:
Component config -> Wi-Fi ->
 - Software controls WiFi/Bluetooth coexistance: works with both settings, default: NO
 - Max number of WiFi static RX buffers: 10 ( no change here? )
 - Max number of WiFi dynamic RX buffers: 32 ( was 0 )
 - Max number of WiFi dynamic TX buffers: 32 ( no change here? )
 - Type of WiFi TX buffers: Dynamic ( no change here? )
 - WiFi AMPDU TX: YES ( no change here? )
 - WiFi AMPDU TX BA window size: 6 ( no change here? )
 - WiFi AMPDU RX: YES ( no change here? )
 - WiFi AMPDU RX BA window size: 6 ( no change here? )
 - WiFi NVS flash: YES ( was NO? )

Also to make it compatible with other defaults, change this:
Component config -> Lua RTOS -> Network services -> SSH Server:
 - Enable SSH server: YES ( was NO, but is YES as default for other boards)

I tested SSH server and it was working with changes I made. One could tweak settings, change RX and TX buffers for example to 16, but I didn't go fiddling with values that I used to get this working.
I tryied similar changes with Generic but didn't got a working WiFi so key is combination of settings that I didn't go mapping.....

So important changes are that both dynamic RX and TX buffers of WiFi should be 32 and WiFi NVS flash should be enabled by default.

Second change that I would do, is to rename board name. Remove OLED definition, because, my board does not have OLED on it - my board is "plain", this one:
https://www.ebay.com/itm/Based-ESP-32-ESP-WROOM-32-4MB-Flash-WEMOS-Lolin32-V1-0-0-WIFI-Bluetooth-Card/263268761505?hash=item3d4c0a7fa1:g:o-0AAOSwHYpZ51Y9

One can most probably add OLED easily by stacking a shield like this (pin mapping seems pretty compatible to adafruit feather/huzzah): https://www.ebay.com/itm/FeatherWing-OLED-128x32-OLED-Add-on-For-All-Feather-Boards/252569794693?epid=1390787320&hash=item3ace553885:g:rgYAAOSwLnBX8-A~

There are many kinds of Wemos Lolin32/esp32 boards, and this seems to work with most of them, I also have board like this:
https://www.ebay.com/itm/TTGO-MINI-Wemos-D1-ESP32-ESP-32-WIFI-Development-Bluetooth-ESP8266-CP2104-Module/202102850130?hash=item2f0e44c252:g:1wIAAOSw6GJZ~Klr

But unfortunately I was not able to get WiFi to work with that - both scanning for available networks or trying to connect caused a reboot because of browning out - but it is possible that my board is defective (it was cheap, so....) because I also tested for WiFi functionality with building a simple Arduino application (one that scans for available networks, and one that just connects to network and then sits there) - I was not able to get either of them to work, brownout issue there too. With another board also Arduino code worked perfectly. This board is called WEMOS MINI32.
Most likely issue is because of defective board - because I just realized that I have another one of these, decided to try with that, but that board was defective also, in a different way - USB power did not power the board at all. It seems that WEMOS MINI32 is one of those boards that are very low quality. Hopefully someone else with such board would give it a go and hopefully get it working. In any case though, I don't recommend WEMOS MINI32 (TTGO) because I have 2 and both were rubbish.

WEMOS LOLIN32 and similar boards are cheap. But when something is cheap, cost might be elsewhere, according to this document, it's a bug:
https://hackaday.com/2017/05/03/hands-on-hot-new-wemos-esp-32-breakout/

But this doesn't mean that board is completely useless. In any case, it's a great board if one wants to test LUA-RTOS-ESP32 with a cheap board. And most probably it will also be useful in most cases.

I have ordered a Adafruit Feather Huzzah ESP32 and will be testing that one too when it arrives in a few weeks. WEMOS LOLIN32 is a cheap copy of it. (costs 25% of huzzah and is said to be compatible).
I think LUA-RTOS-ESP32 is great, and should be made compatible with more boards :)

Any way, this patch with minor changes should be merged :)

**Comment by bytebang** [comment]
Sorry - I disabled SSH by accident. You are right it should be turned on.
My WiFi is working fine. I am able to ping the device, and it is also able to ping hosts within my network / the internet. There was no need to modify the TX / RX buffers.

I am going to switch on SSH and try it once again.

**Comment by bytebang** [comment]
Hi @oskarirauta 
I have just tried to compile it with the SSH server option. Result: Works without any issues !

Regarding your suggested values with the WiFi {RX,TX} buffers: I have also tried to compile it with and without your suggested values. Both variants are working fine with my board. I have attached my latest configuration where your suggested values are implemented. Since it works without any issues with my board (and this should be true for your board as well) i suggest to use this one for the final patch against LuaRTOS.

Regarding your suggestion to omit the OLED part of the description: If this config works also for other cheap boards (without any display) then this is a good idea. However: I would suggest to leave the following options set:

CONFIG_LUA_RTOS_GDISPLAY_I2C=1
CONFIG_LUA_RTOS_I2C1_SCL=4
CONFIG_LUA_RTOS_I2C1_SDA=5

They are responsible for the GLCD which comes with some boards (at least with my board).

One last thing regarding SSH: It seems that dropbear is starting as needed, but in the end I am no able to connect to the ESP32 because of the following message:

image

 

Can you confirm that this config works for your board as well ? 

[WeMos-Lolin32.zip](https://github.com/whitecatboard/Lua-RTOS-ESP32/files/1887653/WeMos-Lolin32.zip)

**Comment by oskarirauta** [comment]
Issue was never related to ssh/dropbear. It was just a note :)

I can set buffers to 16, and it works. But with RX buffer 0 and no nvs, after joining network, Connection is completely muted. I think setting buffers the way I instructed gives more out-of-the-box compatibility than harm. I never touched any display settings, device without display doesn’t care those, and while my device is without display, I am in no place to say anything about display setup :)

Lähetetty iPhonesta

**Comment by oskarirauta** [comment]
I can not confirm until next weekend. I left to work already (truck driver)

Lähetetty iPhonesta

**Comment by oskarirauta** [comment]
I didn't re-compile, but my configuration already matches this configuration so it works.

I never removed lcd configuration.

**Pull request merged**
