### PR TITLE
sync up

### PR DESCRIPTION
**Pull request by the0ne**
didn't find an option to create individual pull requests

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
You must create a new branch on your repo, for example captive-dns. Switch to the new branch. Write the code, and then, do a pull request from the new branch to my repo.

**Comment by thunderWhitecat** [comment]
Prior remove dns captive changes from your master branch and update this pull request. Without this changes this pull request can be merge now.

**Comment by the0ne** [comment]
ok.

**Comment by the0ne** [comment]
ok like this?

**Comment by the0ne** [comment]
i'll create the captivedns pull once this pull is closed.
then the diff should be clean.

**Comment by thunderWhitecat** [comment]
Yes, that's it.

**Comment by thunderWhitecat** [comment]
Pull request merged.

:)

**Comment by the0ne** [comment]
captivedns pull requested as #34

**Pull request merged**
