### PR TITLE
added captive dns service

### PR DESCRIPTION
**Pull request by the0ne**
needs to be started explicitly using net.service.captivedns.start()
error handling in captivedns_start needs to be implemented, see FIXME.

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
Can I ask you for write a wiki page for this? This will be helpful for us ...

This is an example:

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Net-module#wi-fi

**Comment by the0ne** [comment]
No problem.
Do I need special permissions to create new pages?

**Comment by the0ne** [comment]
Think I found the missing link :-) 
Will try it later!

**Comment by thunderWhitecat** [comment]
You can create the page in your repo. Then clone your wiki. Copy the page and commit to the push request as a regular file.

**Comment by the0ne** [comment]
i have added net services to:
https://github.com/the0ne/Lua-RTOS-ESP32/wiki
as
https://github.com/the0ne/Lua-RTOS-ESP32/wiki/Net-services#captive-dns

Didn't find out how to create a PR for the wiki - sorry.

> Copy the page and commit to the push request as a regular file.
Please elaborate what you mean.

**Comment by the0ne** [comment]
Let's please also discuss the following:
https://github.com/the0ne/Lua-RTOS-ESP32/commit/fc6ae5d3b76af1dbfd469e4d3e4c86a4a6ce1fd4

**Comment by thunderWhitecat** [comment]
About "Didn't find out how to create a PR for the wiki - sorry" ....

You can clone a Git Wiki, write the changes locally, and then commit / push to your repository. No pull requests are allowed.

For future contributions it is probably better to incorporate an ".md" file, like "README.md" with the pull request.

**Comment by thunderWhitecat** [comment]
I was thinking about this feature ...

Now user needs:

* Setup wifi in AP
* Start wifi
* Start http
* Start captive DNS

What about to add an additional argument in net.wf.setup function for activate this feature, and start https / captive DNS when wifi starts?

**Comment by the0ne** [comment]
I see what you mean, but i was thinking that the Lua coder wants to decide to sometimes start e.g. http service only, sometimes start http + captive, sometimes luasocket only, sometimes luasocket + captive, etc.

**Comment by the0ne** [comment]
added empty password option...

**Comment by the0ne** [comment]
I think I didn't make my view clear above :-)
I think that the lua coder will actually _want_ single calls as it is now.

**Comment by the0ne** [comment]
Thanks! :+1:

**Comment by thunderWhitecat** [comment]
Thanks to you for the pull request.

**Pull request merged**
