### PR TITLE
Feature for export memory data

### PR DESCRIPTION
**Pull request by zagaria**
Added code for use memory data as a table. I'm using this data as a metrics.

Tested on ESP32 WROVER over 2 weeks

### CODE REVIEW

**Comment by zagaria** [comment]
Hi @jolivepetrus,

Can you, please, review? These changes were tested on real device (ESP32 WROVER) over 2 weeks.

Thanks!

**Comment by the0ne** [comment]
Diff looks backwards compatible and makes sense 👍

**Comment by zagaria** [comment]
Hi @the0ne,

Is it possible to merge this?

Thanks!

**Comment by the0ne** [comment]
Yes I think so. Will try to review tomorrow.

**Comment by the0ne** [comment]
Style isn't really matching the existing code.
Instead of your the many changes, you could just have added something like this, right? Or do I miss something here?

```
    } else if (stat && strcmp(stat,"table") == 0) {
        lua_createtable(L, 0, 0);

        lua_pushstring(L,"free");
        lua_pushinteger(L,xPortGetFreeHeapSize());
        lua_settable(L,-3);

        lua_pushstring(L,"min");
        lua_pushinteger(L,xPortGetMinimumEverFreeHeapSize());
        lua_settable(L,-3);

        return 1;
```

**Comment by the0ne** [comment]
Please reformat your patch to the above, test, and then submit a new PR. I will verify and merge it 👍🏻

**Pull request closed without merging**
