### PR TITLE
the0ne/mqtt_persistence

### PR DESCRIPTION
**Pull request by the0ne**
- moved mqtt closer to paho.mqtt.c source
- enabled mqtt persistence from lua

_please note that SSL SNI does NOT yet work and has been disabled in SSLSocket_setSocketForSSL.
when enabling SSL SNI by uncommenting mbedtls_ssl_set_hostname an ssl handshake failure occurs_

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
I'm not sure about the convenience for the QOS argument in the mqtt.client function. This argument was planned in the :publish function because it may be interesting to publish messages with different QOS values.

**Comment by the0ne** [comment]
Not sure what you mean - please clarify.
mqtt.c has QOS only in lmqtt_subscribe and lmqtt_publish which from mqtt protocol perspective is correct.

Most changes come from upgrading to the current paho impl, i tried to move as close as possible.
Only few changes come from enabling persistency.

**Comment by thunderWhitecat** [comment]
Don't worry.

I was surprised to find a QOS argument in mqtt.client, but if this argument is needed for new versions, not problem. Simply try to add new arguments as optional arguments at the end of the current arguments, to ensure that The Whitecat IDE is not affected.

What is the status of this PR. Is ready to check?.

**Comment by the0ne** [comment]
It was when i requested it :-)
I'll resolve the conflicts and let you know once it's done.

**Comment by the0ne** [comment]
Should be good again now!

**Comment by the0ne** [comment]
@jolivepetrus the PR is ready to check!

**Comment by thunderWhitecat** [comment]
Yes, I know. I expect to have time this week for that.

**Comment by thunderWhitecat** [comment]
@the0ne,

I have tested your PR. I have some suggestions and comments:

1) Not sure about the need of the persistence argument in lmqtt_client. Persistence is implicit when QOS > 0. See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_8.0.0/com.ibm.mq.dev.doc/q029070_.htm:

_"Publication messages are made persistent if they are sent with a quality of service of at least once, or exactly once. You can implement your own persistence mechanism on the client, or use the default persistence mechanism that is provided with the client. Persistence works in both directions, for publications sent to or from the client.
In MQTT, message persistence has two aspects; how the message is transferred, and whether it is queued in IBM® MessageSight and IBM MQ as a persistent message."_

I think that we can assume that when creating a new mqtt client in Lua RTOS this client can be created using file persistence by default.

2) It seems that the persistence directory is created in the current directory. For example, if ypu create a test directory (mkdir test), then change to this directory (cd test) and finally create the mqtt client, the persistence directory is created into the test directory. I suppose that this is a potential issue when the node is restarted and mqtt client is created again from other directory.

**Comment by the0ne** [comment]
Regarding the default I agree that for QOS>0 it makes sense to have persistence enabled by default.
For e.g. my setup - where i only have internal storage and no sd-card or the like - i would not want persistence to be "always-on" or else the spiffs might take several harm over time. So there needs to be some way to turn persistence off.

Yes i agree the persistence folder needs to be set to a fixed absolute path.

**Comment by the0ne** [comment]
As a proposal i will add one more commit that might not be ideal to merge.
Let's possibly discuss this first:

**Comment by the0ne** [comment]
As a proposal i will add one more commit that might not be ideal to merge.
Let's possibly discuss this first:

**Comment by thunderWhitecat** [comment]
Ok, its reasonable.

I suggest the following:

* persistence argument, change type from number to boolean
* add sanity checks in publish & subscribe functions to ensure that if using qos > 0 the persistence is enabled

**Comment by the0ne** [comment]
Implemented as proposed above

**Pull request merged**
