### PR TITLE
Adafruit HUZZAH32 support and some minimal fixes

### PR DESCRIPTION
**Pull request by oskarirauta**
### Contents of pull request
 - Support for ESP32 board [Adafruit HUZZAH32](https://www.adafruit.com/product/3405)
       Board supports "add-on feathers" - kind of a shields, there are some kinds, including a feather with oled display. I have ordered such feather and will make appropriate changes to support display when I receive it.
 - Fixed a typo "Bluetooh" -> "Bluetooth" - not a big deal, but just happened to notice that, so fixed it..
 - Other general standardization, most board configuration files did not have a empty line at EOF, so I removed empty line from these.

### Huzzah32 support
 - WIFI working: GENERIC configuration for Huzzah32, but it did not work (Wifi didn't work), so I build a configuration which targets Huzzah32. One could still use Generic profile and make changes with menuconfig, as changes are minimal (wifi NVS=y and dynamic rx buffers=32), but it's always easier to get started if atleast something works out-of-the-box.
 - General testing and stability seems to be on a good level according to initial testing of board.

### Changes from generic configuration
Board required NVS to get WiFi working. I made some testing at this point and noticed that there are still some connectivity issues; suddenly ping failures started to occur. I changed dynamic RX buffers to 16 and got better results. I also tested with buffers set to 32 but finally falled back to 16 because it seems to work well with that value as well. Issue might had been elsewhere, but there's no problem with dynamic RX buffers, so it would be better to stick with it.
I also did set flash size in configuration to 4MB because this is a 4MB board - even though size is automatically detected by esptool.py; better to be precise instead.

### CODE REVIEW

**Comment by oskarirauta** [comment]
Further testing proved that dynamic rx buffers wasn't the issue, so I reverted that to default setting.

**Comment by oskarirauta** [comment]
Made more testing with Huzzah32 board.
And I am very proud for the results, it's working very well.
I recommend merging this pull request.

During next month I should be able to further improve this by providing support for display feather.

**Comment by oskarirauta** [comment]
Huzzah has 13 actually usable gpio's available for ADC.

I made changes to get them working, but stashed these changes, as it made firmware a bit non-standard and adc drivers become very large (source files) if we start adding custom definitions there... Structural changes might be the answer, but decided for now to stick with standard set of ADC pins.

**Comment by oskarirauta** [comment]
Very nice-

```
/ > uptime
08:13 up  8:31:01
/ > ping 10.0.0.1
PING 10.0.0.1 (10.0.0.1): 32 data bytes
60 bytes from 144.37.254.63: icmp_seq=1 time=3.142 ms
60 bytes from 144.37.254.63: icmp_seq=2 time=1.476 ms
60 bytes from 144.37.254.63: icmp_seq=3 time=1.482 ms
60 bytes from 144.37.254.63: icmp_seq=4 time=1.486 ms
60 bytes from 144.37.254.63: icmp_seq=5 time=1.462 ms
60 bytes from 144.37.254.63: icmp_seq=6 time=1.430 ms
60 bytes from 144.37.254.63: icmp_seq=7 time=6.063 ms
60 bytes from 144.37.254.63: icmp_seq=8 time=2.663 ms
60 bytes from 144.37.254.63: icmp_seq=9 time=1.341 ms
60 bytes from 144.37.254.63: icmp_seq=10 time=1.506 ms
10 packets transmitted, 10 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.341/2.205/6.063/1.412 ms
```

I left it running over night and it hasn't restarted or network connectivity hasn't suffered overtime.

**Comment by thunderWhitecat** [comment]
Nice board!

Can you add in this PR the changes in the ADC for review?

**Comment by oskarirauta** [comment]
I did not do it. It would had been too different from standard Lua-RTOS-ESP32, so I reverted changes that I made, back to standard set. I was thinking- maybe a ”external” adc driver for this platform could do the job- but these are just theories.

Range of default internal adc driver pins is compatible with huzzah, but huzzah does indeed support more adc capable pins that internal driver. Check the specs (and page pinout) for more information about available adc pins

**Comment by oskarirauta** [comment]
Range of internal adc driver pins is compatible with huzzah, but huzzah does indeed support more adc capable pins that internal driver. Check the specs (and page pinout) for more information about available adc pins.

Lähetetty iPhonesta

**Comment by oskarirauta** [comment]
This pull request maybe removed/declined - I re-branched and made a new one.

[deprecated duplicate of 154](https://github.com/whitecatboard/Lua-RTOS-ESP32/pull/154)

**Pull request merged**
