### PR TITLE
the0ne/wps

### PR DESCRIPTION
**Pull request by the0ne**

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
Testing this PR ....

cp file.lua file.lua destroy file. It would be great to detect this situation and show an error message. src and dest paths must be different.

**Comment by thunderWhitecat** [comment]
It would be great to have the wiki pages for wps and smartconfig.

**Comment by thunderWhitecat** [comment]
I'm interested in have more information about the "command line param support for lua_shell". What does this change? An application example?

**Comment by the0ne** [comment]
With this on the lua shell one may enter
> foo.lua bar1 bar2 barX

Inside foo.lua then use
local args={...}

to get a table of all params (bar1 bar2 barX) 

Br
   Thomas


Am 11. Januar 2018 22:46:36 MEZ schrieb "Jaume Olivé Petrus" <notifications@github.com>:

**Comment by the0ne** [comment]
Yes we e.g. need to compare full paths. 

Am 11. Januar 2018 22:42:22 MEZ schrieb "Jaume Olivé Petrus" <notifications@github.com>:

**Pull request merged**
