### PR TITLE
remove build warnings, add httpd lua execution, make encrypted mqtt work

### PR DESCRIPTION
**Pull request by the0ne**
please check the individual commits as they are grouped by topic.
please let me know in case you need me to split this pull request up.

### CODE REVIEW

**Review by thunderWhitecat — APPROVED** [review]

**Comment by jcwren** [comment]
The eliminations of the warnings when compiling is really nice, so thank you for that.  I ran across two while building the latest pull. Default options for ESP32 THING, with LoRa enabled, CAN disabled.
```
CC src/transport.o
/Users/jcw/Projects/Lua-RTOS-ESP32/components/libssh2/./src/transport.c: In function '_libssh2_transport_send':
/Users/jcw/Projects/Lua-RTOS-ESP32/components/libssh2/./src/transport.c:721:79: warning: suggest braces around empty body in an 'if' statement [-Wempty-body]
         debugdump(session, "libssh2_transport_write plain2", data2, data2_len);
                                                                              ^
```

```
CC flash_ops.o
In file included from /Users/jcw/Projects/esp-idf/components/newlib/include/sys/param.h:9:0,
                 from /Users/jcw/Projects/esp-idf/components/spi_flash/./flash_ops.c:19:
/Users/jcw/Projects/esp-idf/components/newlib/include/sys/syslimits.h:52:0: warning: "PATH_MAX" redefined
 #define PATH_MAX   1024 /* max bytes in pathname */
 ^
<command-line>:0:0: note: this is the location of the previous definition
```

**Comment by the0ne** [comment]
i've already seen that libssh2 warning - it came up after i pulled the new files in :-)
that PATH_MAX in esp-idf is fixed locally in my system and it will need a patch-file in Lua-RTOS-ESP32/main/patches/ e.g. syslimits.patch:

> --- ../esp-idf/components/newlib/include/sys/syslimits.h.org	2017-05-05 15:00:31.506717372 +0200
> +++ ../esp-idf/components/newlib/include/sys/syslimits.h	2017-05-16 09:33:08.869216000 +0200
> @@ -49,7 +49,9 @@
>  #ifndef OPEN_MAX
>  #define	OPEN_MAX		   64	/* max open files per process */
>  #endif
> +#ifndef PATH_MAX
>  #define	PATH_MAX		 1024	/* max bytes in pathname */
> +#endif
>  #define	PIPE_BUF		  512	/* max bytes for atomic pipe writes */
>  #define	IOV_MAX			 1024	/* max elements in i/o vector */
>

**Comment by the0ne** [comment]
libssh2 compiler warning is gone with 48e4143ec652bed2deaa23886ea37d7d980c4aa1

**Comment by the0ne** [comment]
@jolivepetrus please update https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Net-module#netwfsetupmode-ssid-password as the parameters have been expanded to:
mode, ssid, password, powersave, channel, hidden

powersave can be 0 (no powersaving) or 1 (powersave modem, see esp code...)
channel is the channel to use for the soft-ap in ap-mode or the channel to start the search for the given ssid when in sta-mode
hidden is only relevant for ap-mode and sets if the new soft-ap ssid should be visible or not

**Comment by thunderWhitecat** [comment]
Removed warning builds described above.

**Comment by thunderWhitecat** [comment]
Some adds in wi-fi driver:

https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/356d2c5d201e0ad3a9854800df22b12e473ebdc8
https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/07bbe5ae1888c61cbe2913a15e5b0371c05d0f07
https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/736d8ea2dd28ff69f51e43c83715e2cd01597cb5
https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/06c9c5cb57013ccc064019b50799b1bd7fe53988

**Comment by the0ne** [comment]
Great! :+1:

**Comment by thunderWhitecat** [comment]
https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Net-module#netwfsetupmode-ssid-password updated. If you can, take a look and tell me if something is wrong.

**Comment by the0ne** [comment]
Looks great!
I plan to add a (tiny) Captive-Mode DNS Server so that the user will automatically be forwarded to (whatever) esp32 http server and doesn't manually need to open his browser and enter the esp32 soft-AP's fixed IP address.

**Pull request merged**
