### PR TITLE
Add wESP32 support

### PR DESCRIPTION
**Pull request by xorbit**
Add board support for the wESP32 (https://hackaday.io/project/85389-wesp32-wired-esp32-with-ethernet-and-poe) which is going to be released on Crowd Supply shortly.

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
@xorbit,

Thanks for this PR. Now, I'm introducing some changes about the Lua RTOS partition structure, and some new file systems. Also, I'm reviewing all the supported boards.

I need the USB VID:PID to include your board. You can get this info with:

python -m serial.tools.list_ports -v

I will try to include it as soon as possible.

**Comment by thunderWhitecat** [comment]
@xorbit,

Also it will be useful if we can have a free sample of this board.

**Comment by xorbit** [comment]
Hello Jaume,

Here's the info for the port:

/dev/ttyUSB0        
    desc: CP2102N USB to UART Bridge Controller
    hwid: USB VID:PID=10C4:EA60 SER=a6fc30ea4620e811b38d29304344cc29 LOCATION=3-2

A free sample is difficult at the moment because I only have one sample left myself until I receive production stock, the other prototypes have been sent to Crowd Supply for the campaign and reviewers, etc.

Thanks!

**Comment by sodabrew** [comment]
@xorbit I just received a wESP32 board from Crowd Supply. Per the documentation on https://wesp32.com/software/, it sounds like there's active interest in merging board support upstream.

Is it possible to take a moment to update this PR and work with the repo maintainers to get it into mergeable state?

**Comment by thunderWhitecat** [comment]
@xorbit, @sodabrew,

Merged in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/cf76480e94cc3fd1569cbf76de5d8db4c7407da3.

Thanks for this PR.

Remind that support for this board through wcc tool (official build) can take up to 24 hours to be published.

**Comment by xorbit** [comment]
I take it it was already in a mergeable state? Thanks for merging!

**Pull request merged**
