### PR TITLE
wifi +httpsrv fix

### PR DESCRIPTION
**Pull request by the0ne**
didn't manage to make the pull request cleaner this time again. sorry. but please check the diff:

linenoise history is fixed.
wifi and httpsrv are **greatly** improved.

an improved lua interpreter is planned for httpsrv as next step. i was thinking about
> &lt;?lua
> print("foo")
> ?&gt;

or do you think

> &lt;?
> print("foo")
> ?&gt;

is better?

### CODE REVIEW

**Comment by jcwren** [comment]
I like <?lua simply to reduce the chance for anyone to ever mistake it for PHP code.

**Comment by thunderWhitecat** [comment]
I'm agree with @jcwren. <?lua ?> is better.

**Comment by the0ne** [comment]
just found a regression in the httpsvr.
please hold.

**Comment by thunderWhitecat** [comment]
Not sure about "fix storage of the linenoise history". This is not a bug. The check was introduced to avoid using history when using SPI flash as storage, due to the limit of 100.000 write in NAND flash.

**Comment by the0ne** [comment]
oh, i see. didn't realize that was the reason :-)
should we then at least put the last X commands into some memory buffer?

**Comment by the0ne** [comment]
looks like the httpsrv changes were too good to be true.
oddly it still works in the test setup, but not with real mobile devices.
i'll possibly just create a pull request with linenoise and httpsrv changes removed.

**Comment by thunderWhitecat** [comment]
A hard work was done in Lua RTOS for save memory (Lua READONLY tables, for example) ... Having a linenoise buffer in memory breaks with this concept.

Programmers can use The Whitecat IDE for develop programs (https://ide.whitecatboard.org), and virtually is not need to access the Lua RTOS console.

Perhaps, if we introduce some type of configuration in Kconfig, for example into Lua RTOS -> General -> Line history:

Enable history if storage is SPI FLASH (disabled by defult)
Enable history in RAM (disabled by default)
....

.... it is the programmer's responsability to enable it or not to enable it.

**Comment by the0ne** [comment]
regarding memory: agreed. absolutely :-)

i've updated httpsrv.c
the solution is **not** as elegant as i wanted it to be because:
* the listening port is not closed, hence
* the listening port is not available to other esp32 apps

but it's an improvement because now lua scripts can start/stop the httpsrv and
* the httpsrv will actually respond/not respond
* the resouces (well, at least the thread) will actually be freed

restarting httpsrv may especially be required when being in a wifi at first, then switching to soft-AP for captive-dns. this is because only after stop -> start the httpsrv will re-read the current esp32 ip address and accept it as a valid "Host:" header instead of redirecting.

please review, test and feedback!

**Review by thunderWhitecat — CHANGES_REQUESTED** [review]
Remove this before merge (https://github.com/whitecatboard/Lua-RTOS-ESP32/pull/48/commits/20ca9a3a26f90a697e626c7b3c86c9b1908eef6b)

**Comment by the0ne** [comment]
removed 20ca9a3a26f90a697e626c7b3c86c9b1908eef6b
added proper lua interpretion (removes the previous stdout "solution")
so now you can write code like

> &lt;?lua
> require('common-http')
> get = parseurl(http_request)
> ?>
> &lt;html>
> &lt;head>&lt;title>ESP32 settings page&lt;/title>&lt;/head>
> &lt;body>
> ssid: &lt;?lua net.service.http.print_chunk(get.ssid) ?>&lt;br />
> pass: &lt;?lua net.service.http.print_chunk(get.pass) ?>&lt;br />
> &lt;/body>
> &lt;/html>

and the httpsrv takes care to pass through the html and interpret the lua code.
for a sample of common-http.lua see 49f9f2c568f7b570e7623cae4b7f6b52bc9679aa

**Comment by thunderWhitecat** [comment]
I think that will be great to add some settings in Kconfig:

	  menu "HTTP server"
		config LUA_RTOS_USE_HTTP_SERVER
			depends on (WIFI_ENABLED || ETHERNET) && LUA_RTOS_LUA_USE_NET
		  	bool "Enable HTTP server"
		  	default y

		config LUA_RTOS_HTTP_SERVER_PORT
			depends on LUA_RTOS_USE_HTTP_SERVER
		    int "HTTP server port"
		    range 0 65536
		    default 80
			help
				TCP port where HTTP server listens.

		config LUA_RTOS_HTTP_SERVER_DOCUMENT_ROOT
			depends on LUA_RTOS_USE_HTTP_SERVER
		    string "HTTP document root"
		    default /
	  endmenu

I have test http server (with out master branch) in STA mode, and allways is redirect to captive dns.

**Comment by the0ne** [comment]
Hmm, that's interesting.
Please note that httpsrv checks wifi mode only on startup.
So you best switch to wifi sta and then stop+start httpsrv.
Does that solve the issue?

**Comment by the0ne** [comment]
Please test configurable port + document root setting.

Once i got some time i'll have a look on how the httpserv can get an event in case wifi network changes.
Then it won't be necessary for the user to stop+start the http server when switching from AP to STA mode.

**Comment by thunderWhitecat** [comment]
Perfect, I will try soon.

Now I'm involved in some refactory about the Lua RTOS event module. You will probably be able to use it for what you need.

What exactly is the problem that requires to stop+start the http server when switching from AP to STA mode?

**Comment by the0ne** [comment]
1) the wifi mode itself (captivedns redirect only makes sense in AP mode)
2) the current IP address needs to be re-read as it changes when switching wifi mode (avoid redirect in case of direct access with IP as Host: header)

_one could argue that 2) is unnecessary because the IP is static anyway - but i'm pretty sure that the AP IP will be configurable in the future, at least compile time and somewhen possibly even at runtime as well._

**Comment by thunderWhitecat** [comment]
Mmmmmm ....

In theory if there is a network change, such us the IP, http server it should not reboot, because the http listens on all interfaces (INADDR_ANY):

	sin.sin_family      = AF_INET;
	sin.sin_addr.s_addr = INADDR_ANY;
	sin.sin_port        = htons(PORT);
	bind(server, (struct sockaddr *) &sin, sizeof (sin));

Maybe is needed to set the SO_REUSEADDR option using setsockopt function ....

**Comment by the0ne** [comment]
It's not about the socket - that works is fine.
It's only about the wifi mode and soft-AP IP.
If i'd re-read that for every request then a restart of the httpsrv would not be necessary at all.

**Comment by thunderWhitecat** [comment]
Tested: Configurable port + document root setting.

All OK!

**Comment by thunderWhitecat** [comment]
I think that your first approach about redirecting the stdout it's a very, very good solution, because programmer don't need to use any additional api (net.service.http.print_chunk). Programmer can use standard Lua functions, such as print, io.write, etc ...

No problem about redirecting the stdout, because the process function runs in a thread. Each thread, in Lua RTOS can have it's own stdout.

Any reason for use net.service.http.print_chunk?

**Comment by the0ne** [comment]
Yes. It didn't work well.
Httpsrv would output html directly and lua would write to stdout as well.
The main problem was that stdout didn't seem to be synced well between those two. Flushing didn't help/work either.
Next problem was that output was expected (by the client browser) to be chunked but standard lua output isn't chunked of cause. That could have been circumvented by changing from chunked to standard transmission of cause.

Anyway i thought in most cases it shouldn't be too much of an issue to get the desired output and call net.service.http.print_chunk. But as i'm really new to Lua please tell me if i'm wrong :-)

**Comment by thunderWhitecat** [comment]
Yes, you are right about that client expect chunks.

One additional problem is that something like this is not supported:

```lua
<?lua if condition then ?>
<p>true</p>
<?lua else ?>
<p>false</p>
<?lua end ?>
```

I have created a preprocessor for solve this situation. For example, if the lua page is:

```lua
<html>
<head><title>Test Page</title></head>
<body>
Hi from lua
<?lua if true then ?>
<p>true</p>
<?lua else ?>
<p>false</p>
<?lua end ?>
<br />
</body>
</html>
```

.... the preprocessor generates this output:

```lua
do
local print = net.service.http.print_chunk
print("<html>")
print("<head><title>Test Page</title></head>")
print("<body>")
print("Hi from lua")
 if true then 
print("<p>true</p>")
 else 
print("<p>false</p>")
 end 
print("<br />")
print("</body>")
print("</html>")
end
```

Then, in send file, luaL_dofile ....

Here you are a gist with the affected files:

https://gist.github.com/jolivepetrus/719c4d12f21d66dd18ca75c9f9abf65a
https://gist.github.com/jolivepetrus/becaac2bbcc858f8a46c8bd444606a2c

All code is put in a do ... end statement, and print is redefined as net.service.http.print_chunk as a local variable.

It's only an idea.

**Comment by the0ne** [comment]
Looks like you're reading my ToDo list ;-D

**Comment by thunderWhitecat** [comment]
I'm trying to create something in the github's orgnization for mantain a ToDo list.

**Comment by thunderWhitecat** [comment]
@the0ne, you can use the net_event_register_callback / net_event_unregister_callback functions in order to know the network changes from the http server.

See commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/fb63839a001ddd98b3d791c5894e6c022d4518f0.

**Pull request merged**
