### PR TITLE
remove libssl2 build warnings

### PR DESCRIPTION
**Pull request by the0ne**
+added some common aliases
esp-idf needs a patch file (i'll prepare it)

### CODE REVIEW

**Comment by the0ne** [comment]
i just realized we were doing .patch-file work in parallel so i'll stop that effort now.

**Comment by thunderWhitecat** [comment]
@the0ne, sorry I have commented in https://github.com/whitecatboard/Lua-RTOS-ESP32/pull/30 that proposed changes related to build warnings was done.

**Comment by the0ne** [comment]
please check the captive dns service if possible.
there's two FIXME mentioned in 1ace77d92633d1b7201d7bd176c465a64a3240ba with regards to error handling.
apart from that it should work :-)

**Comment by thunderWhitecat** [comment]
@theOne, I think that is better to split individual work in independent pull requests. Captive dns should be in a new pull request. This allows to test each pull request.

**Comment by the0ne** [comment]
it's a mess.
i'll create a new pull request - not sure how to include only certain files, tough.
you can check the diff at https://github.com/whitecatboard/Lua-RTOS-ESP32/compare/master...the0ne:master

**Pull request closed without merging**
