### PR TITLE
Curl module added

### PR DESCRIPTION
**Pull request by loboris**
Implemented some functions for http, ftp, smtp protocols, based on libcurl library.
SSL/TLS is fully supported.
Function's sintax and examples available in _net_service_curl.inc_

 *  It is recommended to set **CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN** to 8192 or 4096  in mbedTLS section to avoid 'out of memory'  when using SSL/TLS transfers
 *
 *  **CONFIG_TCPIP_TASK_STACK_SIZE** has to be at least 4096

-----------------------------------------------------------------------------------------------------------

**There is one problem related to NET_VFS:**

If NET_VFS is defined, and it is always defined if CONFIG_WIFI_ENABLED or CONFIG_ETHERNET is defined, the following problem is present:

Socket fd returned by **socket()** function is not the fd returned by **lwip_socket()**, but the file descriptor returned by **fopen("/dev/socket/n","a+")** in **__wrap_lwip_socket()**, which causes **closesocket()** (lwip_close()) not to close the socket properly.

**This problem affects all functions which uses closesocket() function (ping(), ...).
None of those functions closes the socket properly.**

As a temporary  workaround, variable **_curl_socket** is added to **lua_rtos/lwip/socket.c** which tells **__wrap_lwip_socket()** to return the original **lwip_socket()** fd if set to 1

**More elegant solution should be found**, as this one works only for curl module's functions.

I don't see if **net vfs** is used anywhere in Lua-RTOS-ESP32, maybe it coud be be disabled altogether.

### CODE REVIEW

**Comment by thunderWhitecat** [comment]
Hi @loboris,

When build this pull request we receive this build error:

In file included from /Users/jolive/Lua-RTOS-ESP32/components/curl/lib/amigaos.c:23:0:
/Users/jolive/Lua-RTOS-ESP32/components/curl/lib/curl_setup.h:41:25: fatal error: curl_config.h: No such file or directory

Tested in Mac OS.

**Comment by loboris** [comment]
Hi,
I've only tested it under Linux and never had any problems.
Could you try to build the standalone esp-idf example from
[ESP32_curl_example](https://github.com/loboris/ESP32_curl_example)
to see if there is the same error.
It has to be related to your Mac OS build environment

Best Regards

**Comment by the0ne** [comment]
@loboris looks like both
curl_config.h **and**
curl_config.h.in
are in your .gitignore file.

**Comment by loboris** [comment]
Thanks, those files are in .gitignore in original libcurl repository.
I've removed them and pushed the changes, you should be able to build it now.

Best regards.

**Comment by thunderWhitecat** [comment]
Hi @loboris,

Great work! We have some comments about this pull request:

* Mac OSX needs additional changes for build. Attached you have the modified components.mk.

[components.mk.txt](https://github.com/whitecatboard/Lua-RTOS-ESP32/files/1000945/components.mk.txt)

* The new functions are located in net.service.xxxx. In our original design this was reserved for services that runs always in the Lua RTOS background, for example net.service.http.start(). May be is better to locate new functions under net.xxx for coherency.

* If I'm not wrong this pull request includes more than curl, I can see functions for send mails (great!!!). Probably it's better, in the Lua part to put curl functions into net.curl.xxx and mail functions into net.mail.xxx.

**Comment by thunderWhitecat** [comment]
Proposed:

net.http.XXX
net.ftp.XXX
net.mail.XXX

**Comment by thunderWhitecat** [comment]
Hi @loboris,

Please, try this commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/3d2ad9fcf586253b18c12f2a32dd846a5f3250e9. It resolves a potential bug in NET VFS implementation. Maybe the issue you commented above.

**Comment by thunderWhitecat** [comment]
@loboris, sorry for my comments:

net.http.XXX
net.ftp.XXX
net.mail.XXX

.... I was thinking in php_curl ... :(

Pull request merged to master.

**Pull request merged**
